/**
 * Shared constants and utilities for PDF report generation.
 *
 * @license AGPL-3.0
 */

/** Left/right/top margin in points. */
export const MARGIN = 50;

/** US Letter page width in points. */
export const PAGE_WIDTH = 612;

/** US Letter page height in points. */
export const PAGE_HEIGHT = 792;

/** Printable content width (page minus both margins). */
export const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

/** Bottom boundary for content (above footer). */
export const PAGE_BOTTOM = PAGE_HEIGHT - MARGIN - 20;

/** Height of each data row in points. */
export const LINE_HEIGHT = 14;

/** Height of the global page header (title + subtitle + year/box info). */
export const GLOBAL_HEADER_HEIGHT = 50;

/** Height of a box section label + column headers + separator. */
export const BOX_SECTION_HEIGHT = 38;

/** Height of the summary totals block. */
export const SUMMARY_HEIGHT = 30;

/** @deprecated Use flow-based layout instead of fixed lines per page. */
export const LINES_PER_PAGE = 14;

/**
 * IRS Form 8949 box descriptions keyed by letter (A–F).
 */
export const BOX_DESCRIPTIONS: Record<string, string> = {
  A: "Short-term — basis reported to IRS",
  B: "Short-term — basis NOT reported to IRS",
  C: "Short-term — not on Form 1099-B",
  D: "Long-term — basis reported to IRS",
  E: "Long-term — basis NOT reported to IRS",
  F: "Long-term — not on Form 1099-B",
};

/**
 * Format a number as US-locale currency string with 2 decimal places.
 *
 * @param n - The number to format
 * @returns Formatted string (e.g. "1,234.56")
 */
export function fmt(n: number): string {
  return n.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

/**
 * Format a value as USD currency, returning "—" for null/undefined.
 */
export function fmtUsd(n: number | null | undefined): string {
  if (n == null) return "—";
  return n.toLocaleString("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2 });
}

/**
 * Add a new page if the remaining vertical space is less than `needed` points.
 */
export function ensureSpace(doc: InstanceType<typeof PDFDocument>, needed: number): void {
  if (doc.y + needed > PAGE_BOTTOM) doc.addPage();
}

/**
 * Render the standard DTax footer at the bottom of a PDF page.
 *
 * @param doc - The PDFKit document instance
 */
export function renderFooter(doc: PDFKit.PDFDocument): void {
  doc
    .fontSize(7)
    .font("Helvetica")
    .fillColor("#888888")
    .text(
      "Generated by DTax (getdtax.com) — For informational purposes only",
      MARGIN,
      740,
      { align: "center", width: CONTENT_WIDTH },
    );
  doc.fillColor("#000000");
}
