/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AiClassifyAllUnknown200ResponseData } from "./ai-classify-all-unknown200-response-data";

export interface AiClassifyAllUnknown200Response {
  data: AiClassifyAllUnknown200ResponseData;
}
