/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CalculateSpecificId200ResponseData {
  results: Array<any>;
  method: MethodEnum;
  taxYear: number;
}

export enum MethodEnum {
  SPECIFIC_ID = "SPECIFIC_ID",
  UNKNOWN_DEFAULT_OPEN_API = "11184809",
}
