/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export enum CostBasisMethod {
  FIFO = "FIFO",
  LIFO = "LIFO",
  HIFO = "HIFO",
  SPECIFIC_ID = "SPECIFIC_ID",
  UNKNOWN_DEFAULT_OPEN_API = "11184809",
}
