/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export enum CsvFormat {
  GENERIC = "generic",
  COINBASE = "coinbase",
  BINANCE = "binance",
  BINANCE_US = "binance_us",
  KRAKEN = "kraken",
  ETHERSCAN = "etherscan",
  ETHERSCAN_ERC20 = "etherscan_erc20",
  GEMINI = "gemini",
  CRYPTO_COM = "crypto_com",
  KUCOIN = "kucoin",
  OKX = "okx",
  BYBIT = "bybit",
  GATE = "gate",
  BITGET = "bitget",
  MEXC = "mexc",
  HTX = "htx",
  SOLSCAN = "solscan",
  SOLSCAN_DEFI = "solscan_defi",
  BITFINEX = "bitfinex",
  POLONIEX = "poloniex",
  KOINLY = "koinly",
  COINTRACKER = "cointracker",
  CRYPTACT = "cryptact",
  UNKNOWN_DEFAULT_OPEN_API = "11184809",
}
