/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SendChatMessage200ResponseData } from "./send-chat-message200-response-data";

export interface SendChatMessage200Response {
  data: SendChatMessage200ResponseData;
}
