/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { TransferMatchOutTx } from "./transfer-match-out-tx";

export interface TransferMatch {
  outTx: TransferMatchOutTx;
  inTx: TransferMatchOutTx;
  amountDiff: number;
  timeDiffMs: number;
}
