/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export enum TxType {
  BUY = "BUY",
  SELL = "SELL",
  TRADE = "TRADE",
  TRANSFER_IN = "TRANSFER_IN",
  TRANSFER_OUT = "TRANSFER_OUT",
  AIRDROP = "AIRDROP",
  STAKING_REWARD = "STAKING_REWARD",
  MINING_REWARD = "MINING_REWARD",
  INTEREST = "INTEREST",
  GIFT_RECEIVED = "GIFT_RECEIVED",
  GIFT_SENT = "GIFT_SENT",
  LOST = "LOST",
  STOLEN = "STOLEN",
  FORK = "FORK",
  MARGIN_TRADE = "MARGIN_TRADE",
  LIQUIDATION = "LIQUIDATION",
  INTERNAL_TRANSFER = "INTERNAL_TRANSFER",
  DEX_SWAP = "DEX_SWAP",
  LP_DEPOSIT = "LP_DEPOSIT",
  LP_WITHDRAWAL = "LP_WITHDRAWAL",
  LP_REWARD = "LP_REWARD",
  WRAP = "WRAP",
  UNWRAP = "UNWRAP",
  BRIDGE_OUT = "BRIDGE_OUT",
  BRIDGE_IN = "BRIDGE_IN",
  CONTRACT_APPROVAL = "CONTRACT_APPROVAL",
  NFT_MINT = "NFT_MINT",
  NFT_PURCHASE = "NFT_PURCHASE",
  NFT_SALE = "NFT_SALE",
  UNKNOWN = "UNKNOWN",
  UNKNOWN_DEFAULT_OPEN_API = "11184809",
}
