/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { TxType } from "./tx-type";

export interface UpdateTransactionRequest {
  type?: TxType;
  timestamp?: string;
  sentAsset?: string;
  sentAmount?: number;
  sentValueUsd?: number;
  receivedAsset?: string;
  receivedAmount?: number;
  receivedValueUsd?: number;
  feeAsset?: string;
  feeAmount?: number;
  feeValueUsd?: number;
  notes?: string;
  tags?: Array<string>;
  sourceId?: string;
}
