/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { ErrorResponse } from "../models";
// @ts-ignore
import type { GetAdminStats200Response } from "../models";
// @ts-ignore
import type { GetAdminUser200Response } from "../models";
// @ts-ignore
import type { ListAdminUsers200Response } from "../models";
// @ts-ignore
import type { UpdateUserRole200Response } from "../models";
// @ts-ignore
import type { UpdateUserRoleRequest } from "../models";
/**
 * AdminApi - axios parameter creator
 */
export const AdminApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * System overview statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAdminStats: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/admin/stats`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get user details by ID
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAdminUser: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("getAdminUser", "id", id);
      const localVarPath = `/api/v1/admin/users/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List all users (paginated)
     * @param {number} [page]
     * @param {number} [limit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listAdminUsers: async (
      page?: number,
      limit?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/admin/users`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Change a user\'s role
     * @param {string} id
     * @param {UpdateUserRoleRequest} updateUserRoleRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateUserRole: async (
      id: string,
      updateUserRoleRequest: UpdateUserRoleRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("updateUserRole", "id", id);
      // verify required parameter 'updateUserRoleRequest' is not null or undefined
      assertParamExists(
        "updateUserRole",
        "updateUserRoleRequest",
        updateUserRoleRequest,
      );
      const localVarPath = `/api/v1/admin/users/{id}/role`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateUserRoleRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AdminApi - functional programming interface
 */
export const AdminApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AdminApiAxiosParamCreator(configuration);
  return {
    /**
     * System overview statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAdminStats(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetAdminStats200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getAdminStats(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AdminApi.getAdminStats"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Get user details by ID
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAdminUser(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetAdminUser200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getAdminUser(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AdminApi.getAdminUser"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List all users (paginated)
     * @param {number} [page]
     * @param {number} [limit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listAdminUsers(
      page?: number,
      limit?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ListAdminUsers200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listAdminUsers(
        page,
        limit,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AdminApi.listAdminUsers"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Change a user\'s role
     * @param {string} id
     * @param {UpdateUserRoleRequest} updateUserRoleRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateUserRole(
      id: string,
      updateUserRoleRequest: UpdateUserRoleRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<UpdateUserRole200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateUserRole(
        id,
        updateUserRoleRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AdminApi.updateUserRole"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * AdminApi - factory interface
 */
export const AdminApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = AdminApiFp(configuration);
  return {
    /**
     * System overview statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAdminStats(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetAdminStats200Response> {
      return localVarFp
        .getAdminStats(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Get user details by ID
     * @param {AdminApiGetAdminUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAdminUser(
      requestParameters: AdminApiGetAdminUserRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetAdminUser200Response> {
      return localVarFp
        .getAdminUser(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * List all users (paginated)
     * @param {AdminApiListAdminUsersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listAdminUsers(
      requestParameters: AdminApiListAdminUsersRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ListAdminUsers200Response> {
      return localVarFp
        .listAdminUsers(
          requestParameters.page,
          requestParameters.limit,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Change a user\'s role
     * @param {AdminApiUpdateUserRoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateUserRole(
      requestParameters: AdminApiUpdateUserRoleRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UpdateUserRole200Response> {
      return localVarFp
        .updateUserRole(
          requestParameters.id,
          requestParameters.updateUserRoleRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AdminApi - interface
 */
export interface AdminApiInterface {
  /**
   * System overview statistics
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getAdminStats(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetAdminStats200Response>;

  /**
   * Get user details by ID
   * @param {AdminApiGetAdminUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getAdminUser(
    requestParameters: AdminApiGetAdminUserRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetAdminUser200Response>;

  /**
   * List all users (paginated)
   * @param {AdminApiListAdminUsersRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  listAdminUsers(
    requestParameters?: AdminApiListAdminUsersRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ListAdminUsers200Response>;

  /**
   * Change a user\'s role
   * @param {AdminApiUpdateUserRoleRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  updateUserRole(
    requestParameters: AdminApiUpdateUserRoleRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<UpdateUserRole200Response>;
}

/**
 * Request parameters for getAdminUser operation in AdminApi.
 */
export interface AdminApiGetAdminUserRequest {
  readonly id: string;
}

/**
 * Request parameters for listAdminUsers operation in AdminApi.
 */
export interface AdminApiListAdminUsersRequest {
  readonly page?: number;

  readonly limit?: number;
}

/**
 * Request parameters for updateUserRole operation in AdminApi.
 */
export interface AdminApiUpdateUserRoleRequest {
  readonly id: string;

  readonly updateUserRoleRequest: UpdateUserRoleRequest;
}

/**
 * AdminApi - object-oriented interface
 */
export class AdminApi extends BaseAPI implements AdminApiInterface {
  /**
   * System overview statistics
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getAdminStats(options?: RawAxiosRequestConfig) {
    return AdminApiFp(this.configuration)
      .getAdminStats(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get user details by ID
   * @param {AdminApiGetAdminUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getAdminUser(
    requestParameters: AdminApiGetAdminUserRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AdminApiFp(this.configuration)
      .getAdminUser(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List all users (paginated)
   * @param {AdminApiListAdminUsersRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listAdminUsers(
    requestParameters: AdminApiListAdminUsersRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return AdminApiFp(this.configuration)
      .listAdminUsers(requestParameters.page, requestParameters.limit, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Change a user\'s role
   * @param {AdminApiUpdateUserRoleRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public updateUserRole(
    requestParameters: AdminApiUpdateUserRoleRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AdminApiFp(this.configuration)
      .updateUserRole(
        requestParameters.id,
        requestParameters.updateUserRoleRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
