/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { AiClassifyAllUnknown200Response } from "../models";
// @ts-ignore
import type { AiClassifyTransactions200Response } from "../models";
// @ts-ignore
import type { AiClassifyTransactionsRequest } from "../models";
// @ts-ignore
import type { CreateConversation200Response } from "../models";
// @ts-ignore
import type { CreateConversationRequest } from "../models";
// @ts-ignore
import type { DeleteConversation200Response } from "../models";
// @ts-ignore
import type { ErrorResponse } from "../models";
// @ts-ignore
import type { GetAiClassificationStats200Response } from "../models";
// @ts-ignore
import type { GetConversation200Response } from "../models";
// @ts-ignore
import type { ListConversations200Response } from "../models";
// @ts-ignore
import type { SendChatMessage200Response } from "../models";
// @ts-ignore
import type { SendChatMessageRequest } from "../models";
// @ts-ignore
import type { StreamChatMessage200Response } from "../models";
/**
 * AiApi - axios parameter creator
 */
export const AiApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Reclassify all UNKNOWN transactions using AI
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    aiClassifyAllUnknown: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/transactions/ai-classify-all`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Classify specific transactions by ID using AI
     * @param {AiClassifyTransactionsRequest} aiClassifyTransactionsRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    aiClassifyTransactions: async (
      aiClassifyTransactionsRequest: AiClassifyTransactionsRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'aiClassifyTransactionsRequest' is not null or undefined
      assertParamExists(
        "aiClassifyTransactions",
        "aiClassifyTransactionsRequest",
        aiClassifyTransactionsRequest,
      );
      const localVarPath = `/api/v1/transactions/ai-classify`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        aiClassifyTransactionsRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Create a new chat conversation
     * @param {CreateConversationRequest} createConversationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConversation: async (
      createConversationRequest: CreateConversationRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createConversationRequest' is not null or undefined
      assertParamExists(
        "createConversation",
        "createConversationRequest",
        createConversationRequest,
      );
      const localVarPath = `/api/v1/chat/conversations`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createConversationRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Delete a chat conversation
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteConversation: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("deleteConversation", "id", id);
      const localVarPath = `/api/v1/chat/conversations/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get AI classification statistics for current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAiClassificationStats: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/transactions/ai-stats`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get a conversation with all its messages
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getConversation: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("getConversation", "id", id);
      const localVarPath = `/api/v1/chat/conversations/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List user\'s chat conversations (paginated)
     * @param {number} [page]
     * @param {number} [limit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listConversations: async (
      page?: number,
      limit?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/chat/conversations`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Send a message and get AI response
     * @param {string} id
     * @param {SendChatMessageRequest} sendChatMessageRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendChatMessage: async (
      id: string,
      sendChatMessageRequest: SendChatMessageRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("sendChatMessage", "id", id);
      // verify required parameter 'sendChatMessageRequest' is not null or undefined
      assertParamExists(
        "sendChatMessage",
        "sendChatMessageRequest",
        sendChatMessageRequest,
      );
      const localVarPath = `/api/v1/chat/conversations/{id}/messages`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        sendChatMessageRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Send a message and get AI response via SSE stream
     * @param {string} id
     * @param {SendChatMessageRequest} sendChatMessageRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    streamChatMessage: async (
      id: string,
      sendChatMessageRequest: SendChatMessageRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("streamChatMessage", "id", id);
      // verify required parameter 'sendChatMessageRequest' is not null or undefined
      assertParamExists(
        "streamChatMessage",
        "sendChatMessageRequest",
        sendChatMessageRequest,
      );
      const localVarPath =
        `/api/v1/chat/conversations/{id}/messages/stream`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(id)),
        );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        sendChatMessageRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AiApi - functional programming interface
 */
export const AiApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AiApiAxiosParamCreator(configuration);
  return {
    /**
     * Reclassify all UNKNOWN transactions using AI
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async aiClassifyAllUnknown(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<AiClassifyAllUnknown200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.aiClassifyAllUnknown(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AiApi.aiClassifyAllUnknown"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Classify specific transactions by ID using AI
     * @param {AiClassifyTransactionsRequest} aiClassifyTransactionsRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async aiClassifyTransactions(
      aiClassifyTransactionsRequest: AiClassifyTransactionsRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<AiClassifyTransactions200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.aiClassifyTransactions(
          aiClassifyTransactionsRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AiApi.aiClassifyTransactions"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Create a new chat conversation
     * @param {CreateConversationRequest} createConversationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createConversation(
      createConversationRequest: CreateConversationRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<CreateConversation200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.createConversation(
          createConversationRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AiApi.createConversation"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Delete a chat conversation
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteConversation(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<DeleteConversation200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteConversation(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AiApi.deleteConversation"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Get AI classification statistics for current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAiClassificationStats(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetAiClassificationStats200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getAiClassificationStats(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AiApi.getAiClassificationStats"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Get a conversation with all its messages
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getConversation(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetConversation200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getConversation(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AiApi.getConversation"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List user\'s chat conversations (paginated)
     * @param {number} [page]
     * @param {number} [limit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listConversations(
      page?: number,
      limit?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ListConversations200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listConversations(page, limit, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AiApi.listConversations"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Send a message and get AI response
     * @param {string} id
     * @param {SendChatMessageRequest} sendChatMessageRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async sendChatMessage(
      id: string,
      sendChatMessageRequest: SendChatMessageRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<SendChatMessage200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.sendChatMessage(
        id,
        sendChatMessageRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AiApi.sendChatMessage"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Send a message and get AI response via SSE stream
     * @param {string} id
     * @param {SendChatMessageRequest} sendChatMessageRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async streamChatMessage(
      id: string,
      sendChatMessageRequest: SendChatMessageRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<StreamChatMessage200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.streamChatMessage(
          id,
          sendChatMessageRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AiApi.streamChatMessage"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * AiApi - factory interface
 */
export const AiApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = AiApiFp(configuration);
  return {
    /**
     * Reclassify all UNKNOWN transactions using AI
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    aiClassifyAllUnknown(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AiClassifyAllUnknown200Response> {
      return localVarFp
        .aiClassifyAllUnknown(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Classify specific transactions by ID using AI
     * @param {AiApiAiClassifyTransactionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    aiClassifyTransactions(
      requestParameters: AiApiAiClassifyTransactionsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AiClassifyTransactions200Response> {
      return localVarFp
        .aiClassifyTransactions(
          requestParameters.aiClassifyTransactionsRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Create a new chat conversation
     * @param {AiApiCreateConversationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConversation(
      requestParameters: AiApiCreateConversationRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CreateConversation200Response> {
      return localVarFp
        .createConversation(
          requestParameters.createConversationRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Delete a chat conversation
     * @param {AiApiDeleteConversationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteConversation(
      requestParameters: AiApiDeleteConversationRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<DeleteConversation200Response> {
      return localVarFp
        .deleteConversation(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Get AI classification statistics for current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAiClassificationStats(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetAiClassificationStats200Response> {
      return localVarFp
        .getAiClassificationStats(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Get a conversation with all its messages
     * @param {AiApiGetConversationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getConversation(
      requestParameters: AiApiGetConversationRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetConversation200Response> {
      return localVarFp
        .getConversation(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * List user\'s chat conversations (paginated)
     * @param {AiApiListConversationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listConversations(
      requestParameters: AiApiListConversationsRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ListConversations200Response> {
      return localVarFp
        .listConversations(
          requestParameters.page,
          requestParameters.limit,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Send a message and get AI response
     * @param {AiApiSendChatMessageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendChatMessage(
      requestParameters: AiApiSendChatMessageRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SendChatMessage200Response> {
      return localVarFp
        .sendChatMessage(
          requestParameters.id,
          requestParameters.sendChatMessageRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Send a message and get AI response via SSE stream
     * @param {AiApiStreamChatMessageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    streamChatMessage(
      requestParameters: AiApiStreamChatMessageRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<StreamChatMessage200Response> {
      return localVarFp
        .streamChatMessage(
          requestParameters.id,
          requestParameters.sendChatMessageRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AiApi - interface
 */
export interface AiApiInterface {
  /**
   * Reclassify all UNKNOWN transactions using AI
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  aiClassifyAllUnknown(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<AiClassifyAllUnknown200Response>;

  /**
   * Classify specific transactions by ID using AI
   * @param {AiApiAiClassifyTransactionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  aiClassifyTransactions(
    requestParameters: AiApiAiClassifyTransactionsRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<AiClassifyTransactions200Response>;

  /**
   * Create a new chat conversation
   * @param {AiApiCreateConversationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  createConversation(
    requestParameters: AiApiCreateConversationRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<CreateConversation200Response>;

  /**
   * Delete a chat conversation
   * @param {AiApiDeleteConversationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  deleteConversation(
    requestParameters: AiApiDeleteConversationRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<DeleteConversation200Response>;

  /**
   * Get AI classification statistics for current user
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getAiClassificationStats(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetAiClassificationStats200Response>;

  /**
   * Get a conversation with all its messages
   * @param {AiApiGetConversationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getConversation(
    requestParameters: AiApiGetConversationRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetConversation200Response>;

  /**
   * List user\'s chat conversations (paginated)
   * @param {AiApiListConversationsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  listConversations(
    requestParameters?: AiApiListConversationsRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ListConversations200Response>;

  /**
   * Send a message and get AI response
   * @param {AiApiSendChatMessageRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  sendChatMessage(
    requestParameters: AiApiSendChatMessageRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<SendChatMessage200Response>;

  /**
   * Send a message and get AI response via SSE stream
   * @param {AiApiStreamChatMessageRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  streamChatMessage(
    requestParameters: AiApiStreamChatMessageRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<StreamChatMessage200Response>;
}

/**
 * Request parameters for aiClassifyTransactions operation in AiApi.
 */
export interface AiApiAiClassifyTransactionsRequest {
  readonly aiClassifyTransactionsRequest: AiClassifyTransactionsRequest;
}

/**
 * Request parameters for createConversation operation in AiApi.
 */
export interface AiApiCreateConversationRequest {
  readonly createConversationRequest: CreateConversationRequest;
}

/**
 * Request parameters for deleteConversation operation in AiApi.
 */
export interface AiApiDeleteConversationRequest {
  readonly id: string;
}

/**
 * Request parameters for getConversation operation in AiApi.
 */
export interface AiApiGetConversationRequest {
  readonly id: string;
}

/**
 * Request parameters for listConversations operation in AiApi.
 */
export interface AiApiListConversationsRequest {
  readonly page?: number;

  readonly limit?: number;
}

/**
 * Request parameters for sendChatMessage operation in AiApi.
 */
export interface AiApiSendChatMessageRequest {
  readonly id: string;

  readonly sendChatMessageRequest: SendChatMessageRequest;
}

/**
 * Request parameters for streamChatMessage operation in AiApi.
 */
export interface AiApiStreamChatMessageRequest {
  readonly id: string;

  readonly sendChatMessageRequest: SendChatMessageRequest;
}

/**
 * AiApi - object-oriented interface
 */
export class AiApi extends BaseAPI implements AiApiInterface {
  /**
   * Reclassify all UNKNOWN transactions using AI
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public aiClassifyAllUnknown(options?: RawAxiosRequestConfig) {
    return AiApiFp(this.configuration)
      .aiClassifyAllUnknown(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Classify specific transactions by ID using AI
   * @param {AiApiAiClassifyTransactionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public aiClassifyTransactions(
    requestParameters: AiApiAiClassifyTransactionsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AiApiFp(this.configuration)
      .aiClassifyTransactions(
        requestParameters.aiClassifyTransactionsRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Create a new chat conversation
   * @param {AiApiCreateConversationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createConversation(
    requestParameters: AiApiCreateConversationRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AiApiFp(this.configuration)
      .createConversation(requestParameters.createConversationRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Delete a chat conversation
   * @param {AiApiDeleteConversationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteConversation(
    requestParameters: AiApiDeleteConversationRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AiApiFp(this.configuration)
      .deleteConversation(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get AI classification statistics for current user
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getAiClassificationStats(options?: RawAxiosRequestConfig) {
    return AiApiFp(this.configuration)
      .getAiClassificationStats(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get a conversation with all its messages
   * @param {AiApiGetConversationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getConversation(
    requestParameters: AiApiGetConversationRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AiApiFp(this.configuration)
      .getConversation(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List user\'s chat conversations (paginated)
   * @param {AiApiListConversationsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listConversations(
    requestParameters: AiApiListConversationsRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return AiApiFp(this.configuration)
      .listConversations(
        requestParameters.page,
        requestParameters.limit,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Send a message and get AI response
   * @param {AiApiSendChatMessageRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public sendChatMessage(
    requestParameters: AiApiSendChatMessageRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AiApiFp(this.configuration)
      .sendChatMessage(
        requestParameters.id,
        requestParameters.sendChatMessageRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Send a message and get AI response via SSE stream
   * @param {AiApiStreamChatMessageRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public streamChatMessage(
    requestParameters: AiApiStreamChatMessageRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AiApiFp(this.configuration)
      .streamChatMessage(
        requestParameters.id,
        requestParameters.sendChatMessageRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
