/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { AuthResponse } from "../models";
// @ts-ignore
import type { ErrorResponse } from "../models";
// @ts-ignore
import type { ForgotPassword200Response } from "../models";
// @ts-ignore
import type { ForgotPasswordRequest } from "../models";
// @ts-ignore
import type { GetMe200Response } from "../models";
// @ts-ignore
import type { LoginInput } from "../models";
// @ts-ignore
import type { RefreshToken200Response } from "../models";
// @ts-ignore
import type { RegisterInput } from "../models";
// @ts-ignore
import type { ResetPasswordRequest } from "../models";
// @ts-ignore
import type { VerifyEmail200Response } from "../models";
/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Request a password reset email
     * @param {ForgotPasswordRequest} forgotPasswordRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    forgotPassword: async (
      forgotPasswordRequest: ForgotPasswordRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'forgotPasswordRequest' is not null or undefined
      assertParamExists(
        "forgotPassword",
        "forgotPasswordRequest",
        forgotPasswordRequest,
      );
      const localVarPath = `/api/v1/auth/forgot-password`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        forgotPasswordRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get current authenticated user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMe: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/auth/me`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Login with email and password to get a JWT token
     * @param {LoginInput} loginInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    login: async (
      loginInput: LoginInput,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'loginInput' is not null or undefined
      assertParamExists("login", "loginInput", loginInput);
      const localVarPath = `/api/v1/auth/login`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        loginInput,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Refresh JWT token (requires valid existing token)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refreshToken: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/auth/refresh`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Register a new user account
     * @param {RegisterInput} registerInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    register: async (
      registerInput: RegisterInput,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'registerInput' is not null or undefined
      assertParamExists("register", "registerInput", registerInput);
      const localVarPath = `/api/v1/auth/register`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        registerInput,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Reset password using the token from the reset email
     * @param {ResetPasswordRequest} resetPasswordRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    resetPassword: async (
      resetPasswordRequest: ResetPasswordRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'resetPasswordRequest' is not null or undefined
      assertParamExists(
        "resetPassword",
        "resetPasswordRequest",
        resetPasswordRequest,
      );
      const localVarPath = `/api/v1/auth/reset-password`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        resetPasswordRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Verify email address using the token sent via email
     * @param {string} token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    verifyEmail: async (
      token: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'token' is not null or undefined
      assertParamExists("verifyEmail", "token", token);
      const localVarPath = `/api/v1/auth/verify-email`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (token !== undefined) {
        localVarQueryParameter["token"] = token;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration);
  return {
    /**
     * Request a password reset email
     * @param {ForgotPasswordRequest} forgotPasswordRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async forgotPassword(
      forgotPasswordRequest: ForgotPasswordRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ForgotPassword200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.forgotPassword(
        forgotPasswordRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.forgotPassword"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Get current authenticated user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getMe(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetMe200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getMe(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.getMe"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Login with email and password to get a JWT token
     * @param {LoginInput} loginInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async login(
      loginInput: LoginInput,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.login(
        loginInput,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.login"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Refresh JWT token (requires valid existing token)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async refreshToken(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<RefreshToken200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.refreshToken(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.refreshToken"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Register a new user account
     * @param {RegisterInput} registerInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async register(
      registerInput: RegisterInput,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.register(
        registerInput,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.register"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Reset password using the token from the reset email
     * @param {ResetPasswordRequest} resetPasswordRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async resetPassword(
      resetPasswordRequest: ResetPasswordRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ForgotPassword200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.resetPassword(
        resetPasswordRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.resetPassword"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Verify email address using the token sent via email
     * @param {string} token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async verifyEmail(
      token: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<VerifyEmail200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.verifyEmail(
        token,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.verifyEmail"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = AuthApiFp(configuration);
  return {
    /**
     * Request a password reset email
     * @param {AuthApiForgotPasswordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    forgotPassword(
      requestParameters: AuthApiForgotPasswordRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ForgotPassword200Response> {
      return localVarFp
        .forgotPassword(requestParameters.forgotPasswordRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Get current authenticated user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMe(options?: RawAxiosRequestConfig): AxiosPromise<GetMe200Response> {
      return localVarFp
        .getMe(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Login with email and password to get a JWT token
     * @param {AuthApiLoginRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    login(
      requestParameters: AuthApiLoginRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AuthResponse> {
      return localVarFp
        .login(requestParameters.loginInput, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Refresh JWT token (requires valid existing token)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refreshToken(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RefreshToken200Response> {
      return localVarFp
        .refreshToken(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Register a new user account
     * @param {AuthApiRegisterRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    register(
      requestParameters: AuthApiRegisterRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AuthResponse> {
      return localVarFp
        .register(requestParameters.registerInput, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Reset password using the token from the reset email
     * @param {AuthApiResetPasswordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    resetPassword(
      requestParameters: AuthApiResetPasswordRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ForgotPassword200Response> {
      return localVarFp
        .resetPassword(requestParameters.resetPasswordRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Verify email address using the token sent via email
     * @param {AuthApiVerifyEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    verifyEmail(
      requestParameters: AuthApiVerifyEmailRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<VerifyEmail200Response> {
      return localVarFp
        .verifyEmail(requestParameters.token, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AuthApi - interface
 */
export interface AuthApiInterface {
  /**
   * Request a password reset email
   * @param {AuthApiForgotPasswordRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  forgotPassword(
    requestParameters: AuthApiForgotPasswordRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ForgotPassword200Response>;

  /**
   * Get current authenticated user profile
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getMe(options?: RawAxiosRequestConfig): AxiosPromise<GetMe200Response>;

  /**
   * Login with email and password to get a JWT token
   * @param {AuthApiLoginRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  login(
    requestParameters: AuthApiLoginRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<AuthResponse>;

  /**
   * Refresh JWT token (requires valid existing token)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  refreshToken(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<RefreshToken200Response>;

  /**
   * Register a new user account
   * @param {AuthApiRegisterRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  register(
    requestParameters: AuthApiRegisterRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<AuthResponse>;

  /**
   * Reset password using the token from the reset email
   * @param {AuthApiResetPasswordRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  resetPassword(
    requestParameters: AuthApiResetPasswordRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ForgotPassword200Response>;

  /**
   * Verify email address using the token sent via email
   * @param {AuthApiVerifyEmailRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  verifyEmail(
    requestParameters: AuthApiVerifyEmailRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<VerifyEmail200Response>;
}

/**
 * Request parameters for forgotPassword operation in AuthApi.
 */
export interface AuthApiForgotPasswordRequest {
  readonly forgotPasswordRequest: ForgotPasswordRequest;
}

/**
 * Request parameters for login operation in AuthApi.
 */
export interface AuthApiLoginRequest {
  readonly loginInput: LoginInput;
}

/**
 * Request parameters for register operation in AuthApi.
 */
export interface AuthApiRegisterRequest {
  readonly registerInput: RegisterInput;
}

/**
 * Request parameters for resetPassword operation in AuthApi.
 */
export interface AuthApiResetPasswordRequest {
  readonly resetPasswordRequest: ResetPasswordRequest;
}

/**
 * Request parameters for verifyEmail operation in AuthApi.
 */
export interface AuthApiVerifyEmailRequest {
  readonly token: string;
}

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI implements AuthApiInterface {
  /**
   * Request a password reset email
   * @param {AuthApiForgotPasswordRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public forgotPassword(
    requestParameters: AuthApiForgotPasswordRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AuthApiFp(this.configuration)
      .forgotPassword(requestParameters.forgotPasswordRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get current authenticated user profile
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getMe(options?: RawAxiosRequestConfig) {
    return AuthApiFp(this.configuration)
      .getMe(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Login with email and password to get a JWT token
   * @param {AuthApiLoginRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public login(
    requestParameters: AuthApiLoginRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AuthApiFp(this.configuration)
      .login(requestParameters.loginInput, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Refresh JWT token (requires valid existing token)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public refreshToken(options?: RawAxiosRequestConfig) {
    return AuthApiFp(this.configuration)
      .refreshToken(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Register a new user account
   * @param {AuthApiRegisterRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public register(
    requestParameters: AuthApiRegisterRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AuthApiFp(this.configuration)
      .register(requestParameters.registerInput, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Reset password using the token from the reset email
   * @param {AuthApiResetPasswordRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public resetPassword(
    requestParameters: AuthApiResetPasswordRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AuthApiFp(this.configuration)
      .resetPassword(requestParameters.resetPasswordRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Verify email address using the token sent via email
   * @param {AuthApiVerifyEmailRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public verifyEmail(
    requestParameters: AuthApiVerifyEmailRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AuthApiFp(this.configuration)
      .verifyEmail(requestParameters.token, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
