/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { CreateBillingPortal200Response } from "../models";
// @ts-ignore
import type { CreateCheckoutSession200Response } from "../models";
// @ts-ignore
import type { CreateCheckoutSessionRequest } from "../models";
// @ts-ignore
import type { ErrorResponse } from "../models";
// @ts-ignore
import type { GetBillingStatus200Response } from "../models";
// @ts-ignore
import type { HandleStripeWebhook200Response } from "../models";
/**
 * BillingApi - axios parameter creator
 */
export const BillingApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Create a Stripe Customer Portal Session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBillingPortal: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/billing/portal`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Create a Stripe Checkout Session for plan upgrade
     * @param {CreateCheckoutSessionRequest} createCheckoutSessionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCheckoutSession: async (
      createCheckoutSessionRequest: CreateCheckoutSessionRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createCheckoutSessionRequest' is not null or undefined
      assertParamExists(
        "createCheckoutSession",
        "createCheckoutSessionRequest",
        createCheckoutSessionRequest,
      );
      const localVarPath = `/api/v1/billing/checkout`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createCheckoutSessionRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get current subscription status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBillingStatus: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/billing/status`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Stripe webhook handler (signature verification, no JWT auth)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    handleStripeWebhook: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/billing/webhook`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * BillingApi - functional programming interface
 */
export const BillingApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = BillingApiAxiosParamCreator(configuration);
  return {
    /**
     * Create a Stripe Customer Portal Session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createBillingPortal(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<CreateBillingPortal200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.createBillingPortal(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["BillingApi.createBillingPortal"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Create a Stripe Checkout Session for plan upgrade
     * @param {CreateCheckoutSessionRequest} createCheckoutSessionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createCheckoutSession(
      createCheckoutSessionRequest: CreateCheckoutSessionRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<CreateCheckoutSession200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.createCheckoutSession(
          createCheckoutSessionRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["BillingApi.createCheckoutSession"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Get current subscription status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getBillingStatus(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetBillingStatus200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getBillingStatus(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["BillingApi.getBillingStatus"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Stripe webhook handler (signature verification, no JWT auth)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async handleStripeWebhook(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<HandleStripeWebhook200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.handleStripeWebhook(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["BillingApi.handleStripeWebhook"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * BillingApi - factory interface
 */
export const BillingApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = BillingApiFp(configuration);
  return {
    /**
     * Create a Stripe Customer Portal Session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBillingPortal(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CreateBillingPortal200Response> {
      return localVarFp
        .createBillingPortal(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Create a Stripe Checkout Session for plan upgrade
     * @param {BillingApiCreateCheckoutSessionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCheckoutSession(
      requestParameters: BillingApiCreateCheckoutSessionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CreateCheckoutSession200Response> {
      return localVarFp
        .createCheckoutSession(
          requestParameters.createCheckoutSessionRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Get current subscription status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBillingStatus(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetBillingStatus200Response> {
      return localVarFp
        .getBillingStatus(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Stripe webhook handler (signature verification, no JWT auth)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    handleStripeWebhook(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<HandleStripeWebhook200Response> {
      return localVarFp
        .handleStripeWebhook(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * BillingApi - interface
 */
export interface BillingApiInterface {
  /**
   * Create a Stripe Customer Portal Session
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  createBillingPortal(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<CreateBillingPortal200Response>;

  /**
   * Create a Stripe Checkout Session for plan upgrade
   * @param {BillingApiCreateCheckoutSessionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  createCheckoutSession(
    requestParameters: BillingApiCreateCheckoutSessionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<CreateCheckoutSession200Response>;

  /**
   * Get current subscription status
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getBillingStatus(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetBillingStatus200Response>;

  /**
   * Stripe webhook handler (signature verification, no JWT auth)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  handleStripeWebhook(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<HandleStripeWebhook200Response>;
}

/**
 * Request parameters for createCheckoutSession operation in BillingApi.
 */
export interface BillingApiCreateCheckoutSessionRequest {
  readonly createCheckoutSessionRequest: CreateCheckoutSessionRequest;
}

/**
 * BillingApi - object-oriented interface
 */
export class BillingApi extends BaseAPI implements BillingApiInterface {
  /**
   * Create a Stripe Customer Portal Session
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createBillingPortal(options?: RawAxiosRequestConfig) {
    return BillingApiFp(this.configuration)
      .createBillingPortal(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Create a Stripe Checkout Session for plan upgrade
   * @param {BillingApiCreateCheckoutSessionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createCheckoutSession(
    requestParameters: BillingApiCreateCheckoutSessionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return BillingApiFp(this.configuration)
      .createCheckoutSession(
        requestParameters.createCheckoutSessionRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get current subscription status
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getBillingStatus(options?: RawAxiosRequestConfig) {
    return BillingApiFp(this.configuration)
      .getBillingStatus(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Stripe webhook handler (signature verification, no JWT auth)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public handleStripeWebhook(options?: RawAxiosRequestConfig) {
    return BillingApiFp(this.configuration)
      .handleStripeWebhook(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
