/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { ConnectionInput } from "../models";
// @ts-ignore
import type { CreateConnection201Response } from "../models";
// @ts-ignore
import type { ErrorResponse } from "../models";
// @ts-ignore
import type { ListConnections200Response } from "../models";
// @ts-ignore
import type { ListDataSources200Response } from "../models";
// @ts-ignore
import type { RenameDataSource200Response } from "../models";
// @ts-ignore
import type { RenameDataSourceRequest } from "../models";
// @ts-ignore
import type { SyncConnection200Response } from "../models";
/**
 * ConnectionsApi - axios parameter creator
 */
export const ConnectionsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Setup a new exchange API connection
     * @param {ConnectionInput} connectionInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConnection: async (
      connectionInput: ConnectionInput,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'connectionInput' is not null or undefined
      assertParamExists("createConnection", "connectionInput", connectionInput);
      const localVarPath = `/api/v1/connections`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        connectionInput,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Delete a data source (unlinks transactions, does NOT delete them)
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteDataSource: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("deleteDataSource", "id", id);
      const localVarPath = `/api/v1/data-sources/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List all exchange API connections
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listConnections: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/connections`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List all data sources (connections + CSV imports)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listDataSources: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/data-sources`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Rename a data source
     * @param {string} id
     * @param {RenameDataSourceRequest} renameDataSourceRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    renameDataSource: async (
      id: string,
      renameDataSourceRequest: RenameDataSourceRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("renameDataSource", "id", id);
      // verify required parameter 'renameDataSourceRequest' is not null or undefined
      assertParamExists(
        "renameDataSource",
        "renameDataSourceRequest",
        renameDataSourceRequest,
      );
      const localVarPath = `/api/v1/data-sources/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        renameDataSourceRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Trigger sync for a specific exchange connection
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    syncConnection: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("syncConnection", "id", id);
      const localVarPath = `/api/v1/connections/{id}/sync`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ConnectionsApi - functional programming interface
 */
export const ConnectionsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    ConnectionsApiAxiosParamCreator(configuration);
  return {
    /**
     * Setup a new exchange API connection
     * @param {ConnectionInput} connectionInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createConnection(
      connectionInput: ConnectionInput,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<CreateConnection201Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.createConnection(
          connectionInput,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ConnectionsApi.createConnection"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Delete a data source (unlinks transactions, does NOT delete them)
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteDataSource(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteDataSource(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ConnectionsApi.deleteDataSource"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List all exchange API connections
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listConnections(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ListConnections200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listConnections(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ConnectionsApi.listConnections"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List all data sources (connections + CSV imports)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listDataSources(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ListDataSources200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listDataSources(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ConnectionsApi.listDataSources"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Rename a data source
     * @param {string} id
     * @param {RenameDataSourceRequest} renameDataSourceRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async renameDataSource(
      id: string,
      renameDataSourceRequest: RenameDataSourceRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<RenameDataSource200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.renameDataSource(
          id,
          renameDataSourceRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ConnectionsApi.renameDataSource"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Trigger sync for a specific exchange connection
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async syncConnection(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<SyncConnection200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.syncConnection(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ConnectionsApi.syncConnection"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * ConnectionsApi - factory interface
 */
export const ConnectionsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ConnectionsApiFp(configuration);
  return {
    /**
     * Setup a new exchange API connection
     * @param {ConnectionsApiCreateConnectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConnection(
      requestParameters: ConnectionsApiCreateConnectionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CreateConnection201Response> {
      return localVarFp
        .createConnection(requestParameters.connectionInput, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Delete a data source (unlinks transactions, does NOT delete them)
     * @param {ConnectionsApiDeleteDataSourceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteDataSource(
      requestParameters: ConnectionsApiDeleteDataSourceRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<string> {
      return localVarFp
        .deleteDataSource(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * List all exchange API connections
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listConnections(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ListConnections200Response> {
      return localVarFp
        .listConnections(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * List all data sources (connections + CSV imports)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listDataSources(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ListDataSources200Response> {
      return localVarFp
        .listDataSources(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Rename a data source
     * @param {ConnectionsApiRenameDataSourceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    renameDataSource(
      requestParameters: ConnectionsApiRenameDataSourceRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RenameDataSource200Response> {
      return localVarFp
        .renameDataSource(
          requestParameters.id,
          requestParameters.renameDataSourceRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Trigger sync for a specific exchange connection
     * @param {ConnectionsApiSyncConnectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    syncConnection(
      requestParameters: ConnectionsApiSyncConnectionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SyncConnection200Response> {
      return localVarFp
        .syncConnection(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * ConnectionsApi - interface
 */
export interface ConnectionsApiInterface {
  /**
   * Setup a new exchange API connection
   * @param {ConnectionsApiCreateConnectionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  createConnection(
    requestParameters: ConnectionsApiCreateConnectionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<CreateConnection201Response>;

  /**
   * Delete a data source (unlinks transactions, does NOT delete them)
   * @param {ConnectionsApiDeleteDataSourceRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  deleteDataSource(
    requestParameters: ConnectionsApiDeleteDataSourceRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<string>;

  /**
   * List all exchange API connections
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  listConnections(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ListConnections200Response>;

  /**
   * List all data sources (connections + CSV imports)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  listDataSources(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ListDataSources200Response>;

  /**
   * Rename a data source
   * @param {ConnectionsApiRenameDataSourceRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  renameDataSource(
    requestParameters: ConnectionsApiRenameDataSourceRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<RenameDataSource200Response>;

  /**
   * Trigger sync for a specific exchange connection
   * @param {ConnectionsApiSyncConnectionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  syncConnection(
    requestParameters: ConnectionsApiSyncConnectionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<SyncConnection200Response>;
}

/**
 * Request parameters for createConnection operation in ConnectionsApi.
 */
export interface ConnectionsApiCreateConnectionRequest {
  readonly connectionInput: ConnectionInput;
}

/**
 * Request parameters for deleteDataSource operation in ConnectionsApi.
 */
export interface ConnectionsApiDeleteDataSourceRequest {
  readonly id: string;
}

/**
 * Request parameters for renameDataSource operation in ConnectionsApi.
 */
export interface ConnectionsApiRenameDataSourceRequest {
  readonly id: string;

  readonly renameDataSourceRequest: RenameDataSourceRequest;
}

/**
 * Request parameters for syncConnection operation in ConnectionsApi.
 */
export interface ConnectionsApiSyncConnectionRequest {
  readonly id: string;
}

/**
 * ConnectionsApi - object-oriented interface
 */
export class ConnectionsApi extends BaseAPI implements ConnectionsApiInterface {
  /**
   * Setup a new exchange API connection
   * @param {ConnectionsApiCreateConnectionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createConnection(
    requestParameters: ConnectionsApiCreateConnectionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConnectionsApiFp(this.configuration)
      .createConnection(requestParameters.connectionInput, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Delete a data source (unlinks transactions, does NOT delete them)
   * @param {ConnectionsApiDeleteDataSourceRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteDataSource(
    requestParameters: ConnectionsApiDeleteDataSourceRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConnectionsApiFp(this.configuration)
      .deleteDataSource(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List all exchange API connections
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listConnections(options?: RawAxiosRequestConfig) {
    return ConnectionsApiFp(this.configuration)
      .listConnections(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List all data sources (connections + CSV imports)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listDataSources(options?: RawAxiosRequestConfig) {
    return ConnectionsApiFp(this.configuration)
      .listDataSources(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Rename a data source
   * @param {ConnectionsApiRenameDataSourceRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public renameDataSource(
    requestParameters: ConnectionsApiRenameDataSourceRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConnectionsApiFp(this.configuration)
      .renameDataSource(
        requestParameters.id,
        requestParameters.renameDataSourceRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Trigger sync for a specific exchange connection
   * @param {ConnectionsApiSyncConnectionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public syncConnection(
    requestParameters: ConnectionsApiSyncConnectionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConnectionsApiFp(this.configuration)
      .syncConnection(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
