/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { ErrorResponse } from "../models";
// @ts-ignore
import type { GetPortfolioHoldings200Response } from "../models";
/**
 * PortfolioApi - axios parameter creator
 */
export const PortfolioApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Aggregate holdings with optional tax-loss harvesting analysis
     * @param {string} [prices] JSON map of asset prices, e.g. {\&quot;BTC\&quot;:45000}
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPortfolioHoldings: async (
      prices?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/portfolio/holdings`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (prices !== undefined) {
        localVarQueryParameter["prices"] = prices;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PortfolioApi - functional programming interface
 */
export const PortfolioApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    PortfolioApiAxiosParamCreator(configuration);
  return {
    /**
     * Aggregate holdings with optional tax-loss harvesting analysis
     * @param {string} [prices] JSON map of asset prices, e.g. {\&quot;BTC\&quot;:45000}
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPortfolioHoldings(
      prices?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetPortfolioHoldings200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getPortfolioHoldings(prices, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PortfolioApi.getPortfolioHoldings"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * PortfolioApi - factory interface
 */
export const PortfolioApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PortfolioApiFp(configuration);
  return {
    /**
     * Aggregate holdings with optional tax-loss harvesting analysis
     * @param {PortfolioApiGetPortfolioHoldingsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPortfolioHoldings(
      requestParameters: PortfolioApiGetPortfolioHoldingsRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetPortfolioHoldings200Response> {
      return localVarFp
        .getPortfolioHoldings(requestParameters.prices, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PortfolioApi - interface
 */
export interface PortfolioApiInterface {
  /**
   * Aggregate holdings with optional tax-loss harvesting analysis
   * @param {PortfolioApiGetPortfolioHoldingsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getPortfolioHoldings(
    requestParameters?: PortfolioApiGetPortfolioHoldingsRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetPortfolioHoldings200Response>;
}

/**
 * Request parameters for getPortfolioHoldings operation in PortfolioApi.
 */
export interface PortfolioApiGetPortfolioHoldingsRequest {
  /**
   * JSON map of asset prices, e.g. {\&quot;BTC\&quot;:45000}
   */
  readonly prices?: string;
}

/**
 * PortfolioApi - object-oriented interface
 */
export class PortfolioApi extends BaseAPI implements PortfolioApiInterface {
  /**
   * Aggregate holdings with optional tax-loss harvesting analysis
   * @param {PortfolioApiGetPortfolioHoldingsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getPortfolioHoldings(
    requestParameters: PortfolioApiGetPortfolioHoldingsRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return PortfolioApiFp(this.configuration)
      .getPortfolioHoldings(requestParameters.prices, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
