/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { BackfillPrices200Response } from "../models";
// @ts-ignore
import type { BackfillPricesRequest } from "../models";
// @ts-ignore
import type { ErrorResponse } from "../models";
// @ts-ignore
import type { GetExchangeRates200Response } from "../models";
// @ts-ignore
import type { GetHistoricalPrice200Response } from "../models";
// @ts-ignore
import type { GetPrices200Response } from "../models";
// @ts-ignore
import type { GetSupportedTickers200Response } from "../models";
/**
 * PricesApi - axios parameter creator
 */
export const PricesApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Backfill missing USD values for user\'s transactions using historical prices
     * @param {BackfillPricesRequest} backfillPricesRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    backfillPrices: async (
      backfillPricesRequest: BackfillPricesRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'backfillPricesRequest' is not null or undefined
      assertParamExists(
        "backfillPrices",
        "backfillPricesRequest",
        backfillPricesRequest,
      );
      const localVarPath = `/api/v1/prices/backfill`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        backfillPricesRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * USD-relative exchange rates for supported fiat currencies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getExchangeRates: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/prices/exchange-rates`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Fetch historical price for a single asset on a specific date
     * @param {string} asset
     * @param {string} date Date in YYYY-MM-DD format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getHistoricalPrice: async (
      asset: string,
      date: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'asset' is not null or undefined
      assertParamExists("getHistoricalPrice", "asset", asset);
      // verify required parameter 'date' is not null or undefined
      assertParamExists("getHistoricalPrice", "date", date);
      const localVarPath = `/api/v1/prices/history`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (asset !== undefined) {
        localVarQueryParameter["asset"] = asset;
      }

      if (date !== undefined) {
        localVarQueryParameter["date"] = date;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Fetch current USD prices for one or more assets
     * @param {string} assets Comma-separated asset tickers, e.g. BTC,ETH,SOL
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPrices: async (
      assets: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'assets' is not null or undefined
      assertParamExists("getPrices", "assets", assets);
      const localVarPath = `/api/v1/prices`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (assets !== undefined) {
        localVarQueryParameter["assets"] = assets;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List supported asset tickers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSupportedTickers: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/prices/supported`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PricesApi - functional programming interface
 */
export const PricesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = PricesApiAxiosParamCreator(configuration);
  return {
    /**
     * Backfill missing USD values for user\'s transactions using historical prices
     * @param {BackfillPricesRequest} backfillPricesRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async backfillPrices(
      backfillPricesRequest: BackfillPricesRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<BackfillPrices200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.backfillPrices(
        backfillPricesRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PricesApi.backfillPrices"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * USD-relative exchange rates for supported fiat currencies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getExchangeRates(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetExchangeRates200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getExchangeRates(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PricesApi.getExchangeRates"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Fetch historical price for a single asset on a specific date
     * @param {string} asset
     * @param {string} date Date in YYYY-MM-DD format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getHistoricalPrice(
      asset: string,
      date: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetHistoricalPrice200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getHistoricalPrice(
          asset,
          date,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PricesApi.getHistoricalPrice"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Fetch current USD prices for one or more assets
     * @param {string} assets Comma-separated asset tickers, e.g. BTC,ETH,SOL
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPrices(
      assets: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetPrices200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getPrices(
        assets,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PricesApi.getPrices"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List supported asset tickers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getSupportedTickers(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetSupportedTickers200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getSupportedTickers(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PricesApi.getSupportedTickers"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * PricesApi - factory interface
 */
export const PricesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PricesApiFp(configuration);
  return {
    /**
     * Backfill missing USD values for user\'s transactions using historical prices
     * @param {PricesApiBackfillPricesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    backfillPrices(
      requestParameters: PricesApiBackfillPricesRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<BackfillPrices200Response> {
      return localVarFp
        .backfillPrices(requestParameters.backfillPricesRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * USD-relative exchange rates for supported fiat currencies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getExchangeRates(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetExchangeRates200Response> {
      return localVarFp
        .getExchangeRates(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Fetch historical price for a single asset on a specific date
     * @param {PricesApiGetHistoricalPriceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getHistoricalPrice(
      requestParameters: PricesApiGetHistoricalPriceRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetHistoricalPrice200Response> {
      return localVarFp
        .getHistoricalPrice(
          requestParameters.asset,
          requestParameters.date,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Fetch current USD prices for one or more assets
     * @param {PricesApiGetPricesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPrices(
      requestParameters: PricesApiGetPricesRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetPrices200Response> {
      return localVarFp
        .getPrices(requestParameters.assets, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * List supported asset tickers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSupportedTickers(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetSupportedTickers200Response> {
      return localVarFp
        .getSupportedTickers(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PricesApi - interface
 */
export interface PricesApiInterface {
  /**
   * Backfill missing USD values for user\'s transactions using historical prices
   * @param {PricesApiBackfillPricesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  backfillPrices(
    requestParameters: PricesApiBackfillPricesRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<BackfillPrices200Response>;

  /**
   * USD-relative exchange rates for supported fiat currencies
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getExchangeRates(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetExchangeRates200Response>;

  /**
   * Fetch historical price for a single asset on a specific date
   * @param {PricesApiGetHistoricalPriceRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getHistoricalPrice(
    requestParameters: PricesApiGetHistoricalPriceRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetHistoricalPrice200Response>;

  /**
   * Fetch current USD prices for one or more assets
   * @param {PricesApiGetPricesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getPrices(
    requestParameters: PricesApiGetPricesRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetPrices200Response>;

  /**
   * List supported asset tickers
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getSupportedTickers(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetSupportedTickers200Response>;
}

/**
 * Request parameters for backfillPrices operation in PricesApi.
 */
export interface PricesApiBackfillPricesRequest {
  readonly backfillPricesRequest: BackfillPricesRequest;
}

/**
 * Request parameters for getHistoricalPrice operation in PricesApi.
 */
export interface PricesApiGetHistoricalPriceRequest {
  readonly asset: string;

  /**
   * Date in YYYY-MM-DD format
   */
  readonly date: string;
}

/**
 * Request parameters for getPrices operation in PricesApi.
 */
export interface PricesApiGetPricesRequest {
  /**
   * Comma-separated asset tickers, e.g. BTC,ETH,SOL
   */
  readonly assets: string;
}

/**
 * PricesApi - object-oriented interface
 */
export class PricesApi extends BaseAPI implements PricesApiInterface {
  /**
   * Backfill missing USD values for user\'s transactions using historical prices
   * @param {PricesApiBackfillPricesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public backfillPrices(
    requestParameters: PricesApiBackfillPricesRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PricesApiFp(this.configuration)
      .backfillPrices(requestParameters.backfillPricesRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * USD-relative exchange rates for supported fiat currencies
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getExchangeRates(options?: RawAxiosRequestConfig) {
    return PricesApiFp(this.configuration)
      .getExchangeRates(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Fetch historical price for a single asset on a specific date
   * @param {PricesApiGetHistoricalPriceRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getHistoricalPrice(
    requestParameters: PricesApiGetHistoricalPriceRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PricesApiFp(this.configuration)
      .getHistoricalPrice(
        requestParameters.asset,
        requestParameters.date,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Fetch current USD prices for one or more assets
   * @param {PricesApiGetPricesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getPrices(
    requestParameters: PricesApiGetPricesRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PricesApiFp(this.configuration)
      .getPrices(requestParameters.assets, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List supported asset tickers
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getSupportedTickers(options?: RawAxiosRequestConfig) {
    return PricesApiFp(this.configuration)
      .getSupportedTickers(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
