/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { CalculateSpecificId200Response } from "../models";
// @ts-ignore
import type { CalculateSpecificIdRequest } from "../models";
// @ts-ignore
import type { CalculateTax200Response } from "../models";
// @ts-ignore
import type { CompareMethodsRequest } from "../models";
// @ts-ignore
import type { CostBasisMethod } from "../models";
// @ts-ignore
import type { ErrorResponse } from "../models";
// @ts-ignore
import type { Form8949Format } from "../models";
// @ts-ignore
import type { GetAvailableLots200Response } from "../models";
// @ts-ignore
import type { GetScheduleD200Response } from "../models";
// @ts-ignore
import type { GetTaxSummary200Response } from "../models";
// @ts-ignore
import type { ReconcileTaxRequest } from "../models";
// @ts-ignore
import type { RunRiskScan200Response } from "../models";
// @ts-ignore
import type { RunRiskScanRequest } from "../models";
// @ts-ignore
import type { SimulateSaleRequest } from "../models";
// @ts-ignore
import type { TaxCalculateInput } from "../models";
/**
 * TaxApi - axios parameter creator
 */
export const TaxApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Calculate tax using user-selected lots (Specific ID method)
     * @param {CalculateSpecificIdRequest} calculateSpecificIdRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    calculateSpecificId: async (
      calculateSpecificIdRequest: CalculateSpecificIdRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'calculateSpecificIdRequest' is not null or undefined
      assertParamExists(
        "calculateSpecificId",
        "calculateSpecificIdRequest",
        calculateSpecificIdRequest,
      );
      const localVarPath = `/api/v1/tax/calculate-specific`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        calculateSpecificIdRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Run tax calculation for a given year and cost basis method
     * @param {TaxCalculateInput} taxCalculateInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    calculateTax: async (
      taxCalculateInput: TaxCalculateInput,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'taxCalculateInput' is not null or undefined
      assertParamExists("calculateTax", "taxCalculateInput", taxCalculateInput);
      const localVarPath = `/api/v1/tax/calculate`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        taxCalculateInput,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Compare tax impact across all cost basis methods (FIFO, LIFO, HIFO)
     * @param {CompareMethodsRequest} compareMethodsRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    compareMethods: async (
      compareMethodsRequest: CompareMethodsRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'compareMethodsRequest' is not null or undefined
      assertParamExists(
        "compareMethods",
        "compareMethodsRequest",
        compareMethodsRequest,
      );
      const localVarPath = `/api/v1/tax/compare-methods`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        compareMethodsRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List available tax lots for Specific ID cost basis method selection
     * @param {number} year
     * @param {string} [asset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAvailableLots: async (
      year: number,
      asset?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'year' is not null or undefined
      assertParamExists("getAvailableLots", "year", year);
      const localVarPath = `/api/v1/tax/available-lots`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (year !== undefined) {
        localVarQueryParameter["year"] = year;
      }

      if (asset !== undefined) {
        localVarQueryParameter["asset"] = asset;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Generate Form 8949 report in JSON, CSV, PDF, or TXF format
     * @param {number} year
     * @param {CostBasisMethod} [method]
     * @param {Form8949Format} [format]
     * @param {boolean} [strictSilo]
     * @param {boolean} [includeWashSales]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getForm8949: async (
      year: number,
      method?: CostBasisMethod,
      format?: Form8949Format,
      strictSilo?: boolean,
      includeWashSales?: boolean,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'year' is not null or undefined
      assertParamExists("getForm8949", "year", year);
      const localVarPath = `/api/v1/tax/form8949`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (year !== undefined) {
        localVarQueryParameter["year"] = year;
      }

      if (method !== undefined) {
        localVarQueryParameter["method"] = method;
      }

      if (format !== undefined) {
        localVarQueryParameter["format"] = format;
      }

      if (strictSilo !== undefined) {
        localVarQueryParameter["strictSilo"] = strictSilo;
      }

      if (includeWashSales !== undefined) {
        localVarQueryParameter["includeWashSales"] = includeWashSales;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Generate Schedule D summary from Form 8949 data
     * @param {number} year
     * @param {CostBasisMethod} [method]
     * @param {boolean} [strictSilo]
     * @param {boolean} [includeWashSales]
     * @param {number} [lossLimit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getScheduleD: async (
      year: number,
      method?: CostBasisMethod,
      strictSilo?: boolean,
      includeWashSales?: boolean,
      lossLimit?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'year' is not null or undefined
      assertParamExists("getScheduleD", "year", year);
      const localVarPath = `/api/v1/tax/schedule-d`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (year !== undefined) {
        localVarQueryParameter["year"] = year;
      }

      if (method !== undefined) {
        localVarQueryParameter["method"] = method;
      }

      if (strictSilo !== undefined) {
        localVarQueryParameter["strictSilo"] = strictSilo;
      }

      if (includeWashSales !== undefined) {
        localVarQueryParameter["includeWashSales"] = includeWashSales;
      }

      if (lossLimit !== undefined) {
        localVarQueryParameter["lossLimit"] = lossLimit;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get saved tax calculation summary for a year and method
     * @param {number} year
     * @param {CostBasisMethod} [method]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTaxSummary: async (
      year: number,
      method?: CostBasisMethod,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'year' is not null or undefined
      assertParamExists("getTaxSummary", "year", year);
      const localVarPath = `/api/v1/tax/summary`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (year !== undefined) {
        localVarQueryParameter["year"] = year;
      }

      if (method !== undefined) {
        localVarQueryParameter["method"] = method;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Upload 1099-DA CSV and reconcile against DTax calculations
     * @param {ReconcileTaxRequest} reconcileTaxRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconcileTax: async (
      reconcileTaxRequest: ReconcileTaxRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'reconcileTaxRequest' is not null or undefined
      assertParamExists(
        "reconcileTax",
        "reconcileTaxRequest",
        reconcileTaxRequest,
      );
      const localVarPath = `/api/v1/tax/reconcile`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        reconcileTaxRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Run pre-audit risk scan for a tax year
     * @param {RunRiskScanRequest} runRiskScanRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    runRiskScan: async (
      runRiskScanRequest: RunRiskScanRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'runRiskScanRequest' is not null or undefined
      assertParamExists(
        "runRiskScan",
        "runRiskScanRequest",
        runRiskScanRequest,
      );
      const localVarPath = `/api/v1/tax/risk-scan`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        runRiskScanRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Simulate a hypothetical sale to preview tax impact
     * @param {SimulateSaleRequest} simulateSaleRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    simulateSale: async (
      simulateSaleRequest: SimulateSaleRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'simulateSaleRequest' is not null or undefined
      assertParamExists(
        "simulateSale",
        "simulateSaleRequest",
        simulateSaleRequest,
      );
      const localVarPath = `/api/v1/tax/simulate`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        simulateSaleRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TaxApi - functional programming interface
 */
export const TaxApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = TaxApiAxiosParamCreator(configuration);
  return {
    /**
     * Calculate tax using user-selected lots (Specific ID method)
     * @param {CalculateSpecificIdRequest} calculateSpecificIdRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async calculateSpecificId(
      calculateSpecificIdRequest: CalculateSpecificIdRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<CalculateSpecificId200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.calculateSpecificId(
          calculateSpecificIdRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaxApi.calculateSpecificId"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Run tax calculation for a given year and cost basis method
     * @param {TaxCalculateInput} taxCalculateInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async calculateTax(
      taxCalculateInput: TaxCalculateInput,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<CalculateTax200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.calculateTax(
        taxCalculateInput,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaxApi.calculateTax"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Compare tax impact across all cost basis methods (FIFO, LIFO, HIFO)
     * @param {CompareMethodsRequest} compareMethodsRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async compareMethods(
      compareMethodsRequest: CompareMethodsRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetScheduleD200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.compareMethods(
        compareMethodsRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaxApi.compareMethods"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List available tax lots for Specific ID cost basis method selection
     * @param {number} year
     * @param {string} [asset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAvailableLots(
      year: number,
      asset?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetAvailableLots200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getAvailableLots(year, asset, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaxApi.getAvailableLots"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Generate Form 8949 report in JSON, CSV, PDF, or TXF format
     * @param {number} year
     * @param {CostBasisMethod} [method]
     * @param {Form8949Format} [format]
     * @param {boolean} [strictSilo]
     * @param {boolean} [includeWashSales]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getForm8949(
      year: number,
      method?: CostBasisMethod,
      format?: Form8949Format,
      strictSilo?: boolean,
      includeWashSales?: boolean,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getForm8949(
        year,
        method,
        format,
        strictSilo,
        includeWashSales,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaxApi.getForm8949"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Generate Schedule D summary from Form 8949 data
     * @param {number} year
     * @param {CostBasisMethod} [method]
     * @param {boolean} [strictSilo]
     * @param {boolean} [includeWashSales]
     * @param {number} [lossLimit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getScheduleD(
      year: number,
      method?: CostBasisMethod,
      strictSilo?: boolean,
      includeWashSales?: boolean,
      lossLimit?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetScheduleD200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getScheduleD(
        year,
        method,
        strictSilo,
        includeWashSales,
        lossLimit,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaxApi.getScheduleD"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Get saved tax calculation summary for a year and method
     * @param {number} year
     * @param {CostBasisMethod} [method]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTaxSummary(
      year: number,
      method?: CostBasisMethod,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetTaxSummary200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTaxSummary(
        year,
        method,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaxApi.getTaxSummary"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Upload 1099-DA CSV and reconcile against DTax calculations
     * @param {ReconcileTaxRequest} reconcileTaxRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async reconcileTax(
      reconcileTaxRequest: ReconcileTaxRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetScheduleD200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.reconcileTax(
        reconcileTaxRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaxApi.reconcileTax"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Run pre-audit risk scan for a tax year
     * @param {RunRiskScanRequest} runRiskScanRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async runRiskScan(
      runRiskScanRequest: RunRiskScanRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<RunRiskScan200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.runRiskScan(
        runRiskScanRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaxApi.runRiskScan"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Simulate a hypothetical sale to preview tax impact
     * @param {SimulateSaleRequest} simulateSaleRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async simulateSale(
      simulateSaleRequest: SimulateSaleRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetScheduleD200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.simulateSale(
        simulateSaleRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaxApi.simulateSale"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * TaxApi - factory interface
 */
export const TaxApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = TaxApiFp(configuration);
  return {
    /**
     * Calculate tax using user-selected lots (Specific ID method)
     * @param {TaxApiCalculateSpecificIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    calculateSpecificId(
      requestParameters: TaxApiCalculateSpecificIdRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CalculateSpecificId200Response> {
      return localVarFp
        .calculateSpecificId(
          requestParameters.calculateSpecificIdRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Run tax calculation for a given year and cost basis method
     * @param {TaxApiCalculateTaxRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    calculateTax(
      requestParameters: TaxApiCalculateTaxRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CalculateTax200Response> {
      return localVarFp
        .calculateTax(requestParameters.taxCalculateInput, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Compare tax impact across all cost basis methods (FIFO, LIFO, HIFO)
     * @param {TaxApiCompareMethodsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    compareMethods(
      requestParameters: TaxApiCompareMethodsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetScheduleD200Response> {
      return localVarFp
        .compareMethods(requestParameters.compareMethodsRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * List available tax lots for Specific ID cost basis method selection
     * @param {TaxApiGetAvailableLotsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAvailableLots(
      requestParameters: TaxApiGetAvailableLotsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetAvailableLots200Response> {
      return localVarFp
        .getAvailableLots(
          requestParameters.year,
          requestParameters.asset,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Generate Form 8949 report in JSON, CSV, PDF, or TXF format
     * @param {TaxApiGetForm8949Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getForm8949(
      requestParameters: TaxApiGetForm8949Request,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<any> {
      return localVarFp
        .getForm8949(
          requestParameters.year,
          requestParameters.method,
          requestParameters.format,
          requestParameters.strictSilo,
          requestParameters.includeWashSales,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Generate Schedule D summary from Form 8949 data
     * @param {TaxApiGetScheduleDRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getScheduleD(
      requestParameters: TaxApiGetScheduleDRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetScheduleD200Response> {
      return localVarFp
        .getScheduleD(
          requestParameters.year,
          requestParameters.method,
          requestParameters.strictSilo,
          requestParameters.includeWashSales,
          requestParameters.lossLimit,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Get saved tax calculation summary for a year and method
     * @param {TaxApiGetTaxSummaryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTaxSummary(
      requestParameters: TaxApiGetTaxSummaryRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetTaxSummary200Response> {
      return localVarFp
        .getTaxSummary(
          requestParameters.year,
          requestParameters.method,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Upload 1099-DA CSV and reconcile against DTax calculations
     * @param {TaxApiReconcileTaxRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconcileTax(
      requestParameters: TaxApiReconcileTaxRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetScheduleD200Response> {
      return localVarFp
        .reconcileTax(requestParameters.reconcileTaxRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Run pre-audit risk scan for a tax year
     * @param {TaxApiRunRiskScanRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    runRiskScan(
      requestParameters: TaxApiRunRiskScanRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RunRiskScan200Response> {
      return localVarFp
        .runRiskScan(requestParameters.runRiskScanRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Simulate a hypothetical sale to preview tax impact
     * @param {TaxApiSimulateSaleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    simulateSale(
      requestParameters: TaxApiSimulateSaleRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetScheduleD200Response> {
      return localVarFp
        .simulateSale(requestParameters.simulateSaleRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * TaxApi - interface
 */
export interface TaxApiInterface {
  /**
   * Calculate tax using user-selected lots (Specific ID method)
   * @param {TaxApiCalculateSpecificIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  calculateSpecificId(
    requestParameters: TaxApiCalculateSpecificIdRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<CalculateSpecificId200Response>;

  /**
   * Run tax calculation for a given year and cost basis method
   * @param {TaxApiCalculateTaxRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  calculateTax(
    requestParameters: TaxApiCalculateTaxRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<CalculateTax200Response>;

  /**
   * Compare tax impact across all cost basis methods (FIFO, LIFO, HIFO)
   * @param {TaxApiCompareMethodsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  compareMethods(
    requestParameters: TaxApiCompareMethodsRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetScheduleD200Response>;

  /**
   * List available tax lots for Specific ID cost basis method selection
   * @param {TaxApiGetAvailableLotsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getAvailableLots(
    requestParameters: TaxApiGetAvailableLotsRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetAvailableLots200Response>;

  /**
   * Generate Form 8949 report in JSON, CSV, PDF, or TXF format
   * @param {TaxApiGetForm8949Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getForm8949(
    requestParameters: TaxApiGetForm8949Request,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<any>;

  /**
   * Generate Schedule D summary from Form 8949 data
   * @param {TaxApiGetScheduleDRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getScheduleD(
    requestParameters: TaxApiGetScheduleDRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetScheduleD200Response>;

  /**
   * Get saved tax calculation summary for a year and method
   * @param {TaxApiGetTaxSummaryRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getTaxSummary(
    requestParameters: TaxApiGetTaxSummaryRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetTaxSummary200Response>;

  /**
   * Upload 1099-DA CSV and reconcile against DTax calculations
   * @param {TaxApiReconcileTaxRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  reconcileTax(
    requestParameters: TaxApiReconcileTaxRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetScheduleD200Response>;

  /**
   * Run pre-audit risk scan for a tax year
   * @param {TaxApiRunRiskScanRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  runRiskScan(
    requestParameters: TaxApiRunRiskScanRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<RunRiskScan200Response>;

  /**
   * Simulate a hypothetical sale to preview tax impact
   * @param {TaxApiSimulateSaleRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  simulateSale(
    requestParameters: TaxApiSimulateSaleRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetScheduleD200Response>;
}

/**
 * Request parameters for calculateSpecificId operation in TaxApi.
 */
export interface TaxApiCalculateSpecificIdRequest {
  readonly calculateSpecificIdRequest: CalculateSpecificIdRequest;
}

/**
 * Request parameters for calculateTax operation in TaxApi.
 */
export interface TaxApiCalculateTaxRequest {
  readonly taxCalculateInput: TaxCalculateInput;
}

/**
 * Request parameters for compareMethods operation in TaxApi.
 */
export interface TaxApiCompareMethodsRequest {
  readonly compareMethodsRequest: CompareMethodsRequest;
}

/**
 * Request parameters for getAvailableLots operation in TaxApi.
 */
export interface TaxApiGetAvailableLotsRequest {
  readonly year: number;

  readonly asset?: string;
}

/**
 * Request parameters for getForm8949 operation in TaxApi.
 */
export interface TaxApiGetForm8949Request {
  readonly year: number;

  readonly method?: CostBasisMethod;

  readonly format?: Form8949Format;

  readonly strictSilo?: boolean;

  readonly includeWashSales?: boolean;
}

/**
 * Request parameters for getScheduleD operation in TaxApi.
 */
export interface TaxApiGetScheduleDRequest {
  readonly year: number;

  readonly method?: CostBasisMethod;

  readonly strictSilo?: boolean;

  readonly includeWashSales?: boolean;

  readonly lossLimit?: number;
}

/**
 * Request parameters for getTaxSummary operation in TaxApi.
 */
export interface TaxApiGetTaxSummaryRequest {
  readonly year: number;

  readonly method?: CostBasisMethod;
}

/**
 * Request parameters for reconcileTax operation in TaxApi.
 */
export interface TaxApiReconcileTaxRequest {
  readonly reconcileTaxRequest: ReconcileTaxRequest;
}

/**
 * Request parameters for runRiskScan operation in TaxApi.
 */
export interface TaxApiRunRiskScanRequest {
  readonly runRiskScanRequest: RunRiskScanRequest;
}

/**
 * Request parameters for simulateSale operation in TaxApi.
 */
export interface TaxApiSimulateSaleRequest {
  readonly simulateSaleRequest: SimulateSaleRequest;
}

/**
 * TaxApi - object-oriented interface
 */
export class TaxApi extends BaseAPI implements TaxApiInterface {
  /**
   * Calculate tax using user-selected lots (Specific ID method)
   * @param {TaxApiCalculateSpecificIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public calculateSpecificId(
    requestParameters: TaxApiCalculateSpecificIdRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TaxApiFp(this.configuration)
      .calculateSpecificId(
        requestParameters.calculateSpecificIdRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Run tax calculation for a given year and cost basis method
   * @param {TaxApiCalculateTaxRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public calculateTax(
    requestParameters: TaxApiCalculateTaxRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TaxApiFp(this.configuration)
      .calculateTax(requestParameters.taxCalculateInput, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Compare tax impact across all cost basis methods (FIFO, LIFO, HIFO)
   * @param {TaxApiCompareMethodsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public compareMethods(
    requestParameters: TaxApiCompareMethodsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TaxApiFp(this.configuration)
      .compareMethods(requestParameters.compareMethodsRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List available tax lots for Specific ID cost basis method selection
   * @param {TaxApiGetAvailableLotsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getAvailableLots(
    requestParameters: TaxApiGetAvailableLotsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TaxApiFp(this.configuration)
      .getAvailableLots(
        requestParameters.year,
        requestParameters.asset,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Generate Form 8949 report in JSON, CSV, PDF, or TXF format
   * @param {TaxApiGetForm8949Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getForm8949(
    requestParameters: TaxApiGetForm8949Request,
    options?: RawAxiosRequestConfig,
  ) {
    return TaxApiFp(this.configuration)
      .getForm8949(
        requestParameters.year,
        requestParameters.method,
        requestParameters.format,
        requestParameters.strictSilo,
        requestParameters.includeWashSales,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Generate Schedule D summary from Form 8949 data
   * @param {TaxApiGetScheduleDRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getScheduleD(
    requestParameters: TaxApiGetScheduleDRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TaxApiFp(this.configuration)
      .getScheduleD(
        requestParameters.year,
        requestParameters.method,
        requestParameters.strictSilo,
        requestParameters.includeWashSales,
        requestParameters.lossLimit,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get saved tax calculation summary for a year and method
   * @param {TaxApiGetTaxSummaryRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getTaxSummary(
    requestParameters: TaxApiGetTaxSummaryRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TaxApiFp(this.configuration)
      .getTaxSummary(requestParameters.year, requestParameters.method, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Upload 1099-DA CSV and reconcile against DTax calculations
   * @param {TaxApiReconcileTaxRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public reconcileTax(
    requestParameters: TaxApiReconcileTaxRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TaxApiFp(this.configuration)
      .reconcileTax(requestParameters.reconcileTaxRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Run pre-audit risk scan for a tax year
   * @param {TaxApiRunRiskScanRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public runRiskScan(
    requestParameters: TaxApiRunRiskScanRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TaxApiFp(this.configuration)
      .runRiskScan(requestParameters.runRiskScanRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Simulate a hypothetical sale to preview tax impact
   * @param {TaxApiSimulateSaleRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public simulateSale(
    requestParameters: TaxApiSimulateSaleRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TaxApiFp(this.configuration)
      .simulateSale(requestParameters.simulateSaleRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
