/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { ConfirmTransfer200Response } from "../models";
// @ts-ignore
import type { DismissTransfer200Response } from "../models";
// @ts-ignore
import type { ErrorResponse } from "../models";
// @ts-ignore
import type { ListTransferMatches200Response } from "../models";
// @ts-ignore
import type { TransferPairInput } from "../models";
/**
 * TransfersApi - axios parameter creator
 */
export const TransfersApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Confirm a matched pair as internal transfer
     * @param {TransferPairInput} transferPairInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    confirmTransfer: async (
      transferPairInput: TransferPairInput,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'transferPairInput' is not null or undefined
      assertParamExists(
        "confirmTransfer",
        "transferPairInput",
        transferPairInput,
      );
      const localVarPath = `/api/v1/transfers/confirm`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        transferPairInput,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Dismiss a matched pair (mark as reviewed)
     * @param {TransferPairInput} transferPairInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    dismissTransfer: async (
      transferPairInput: TransferPairInput,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'transferPairInput' is not null or undefined
      assertParamExists(
        "dismissTransfer",
        "transferPairInput",
        transferPairInput,
      );
      const localVarPath = `/api/v1/transfers/dismiss`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        transferPairInput,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Detect potential internal transfer pairs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listTransferMatches: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/transfers/matches`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TransfersApi - functional programming interface
 */
export const TransfersApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    TransfersApiAxiosParamCreator(configuration);
  return {
    /**
     * Confirm a matched pair as internal transfer
     * @param {TransferPairInput} transferPairInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async confirmTransfer(
      transferPairInput: TransferPairInput,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ConfirmTransfer200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.confirmTransfer(
        transferPairInput,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransfersApi.confirmTransfer"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Dismiss a matched pair (mark as reviewed)
     * @param {TransferPairInput} transferPairInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async dismissTransfer(
      transferPairInput: TransferPairInput,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<DismissTransfer200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.dismissTransfer(
        transferPairInput,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransfersApi.dismissTransfer"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Detect potential internal transfer pairs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listTransferMatches(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ListTransferMatches200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listTransferMatches(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransfersApi.listTransferMatches"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * TransfersApi - factory interface
 */
export const TransfersApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = TransfersApiFp(configuration);
  return {
    /**
     * Confirm a matched pair as internal transfer
     * @param {TransfersApiConfirmTransferRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    confirmTransfer(
      requestParameters: TransfersApiConfirmTransferRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ConfirmTransfer200Response> {
      return localVarFp
        .confirmTransfer(requestParameters.transferPairInput, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Dismiss a matched pair (mark as reviewed)
     * @param {TransfersApiDismissTransferRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    dismissTransfer(
      requestParameters: TransfersApiDismissTransferRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<DismissTransfer200Response> {
      return localVarFp
        .dismissTransfer(requestParameters.transferPairInput, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Detect potential internal transfer pairs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listTransferMatches(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ListTransferMatches200Response> {
      return localVarFp
        .listTransferMatches(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * TransfersApi - interface
 */
export interface TransfersApiInterface {
  /**
   * Confirm a matched pair as internal transfer
   * @param {TransfersApiConfirmTransferRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  confirmTransfer(
    requestParameters: TransfersApiConfirmTransferRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ConfirmTransfer200Response>;

  /**
   * Dismiss a matched pair (mark as reviewed)
   * @param {TransfersApiDismissTransferRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  dismissTransfer(
    requestParameters: TransfersApiDismissTransferRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<DismissTransfer200Response>;

  /**
   * Detect potential internal transfer pairs
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  listTransferMatches(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ListTransferMatches200Response>;
}

/**
 * Request parameters for confirmTransfer operation in TransfersApi.
 */
export interface TransfersApiConfirmTransferRequest {
  readonly transferPairInput: TransferPairInput;
}

/**
 * Request parameters for dismissTransfer operation in TransfersApi.
 */
export interface TransfersApiDismissTransferRequest {
  readonly transferPairInput: TransferPairInput;
}

/**
 * TransfersApi - object-oriented interface
 */
export class TransfersApi extends BaseAPI implements TransfersApiInterface {
  /**
   * Confirm a matched pair as internal transfer
   * @param {TransfersApiConfirmTransferRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public confirmTransfer(
    requestParameters: TransfersApiConfirmTransferRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TransfersApiFp(this.configuration)
      .confirmTransfer(requestParameters.transferPairInput, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Dismiss a matched pair (mark as reviewed)
   * @param {TransfersApiDismissTransferRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public dismissTransfer(
    requestParameters: TransfersApiDismissTransferRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TransfersApiFp(this.configuration)
      .dismissTransfer(requestParameters.transferPairInput, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Detect potential internal transfer pairs
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listTransferMatches(options?: RawAxiosRequestConfig) {
    return TransfersApiFp(this.configuration)
      .listTransferMatches(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
