/* tslint:disable */
/* eslint-disable */
/**
 * DTax API
 * Open-source crypto tax calculation and portfolio management API.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { BulkDeleteTransactions200Response } from "../models";
// @ts-ignore
import type { BulkDeleteTransactionsRequest } from "../models";
// @ts-ignore
import type { CreateTransaction201Response } from "../models";
// @ts-ignore
import type { CreateTransactionInput } from "../models";
// @ts-ignore
import type { CsvFormat } from "../models";
// @ts-ignore
import type { ErrorResponse } from "../models";
// @ts-ignore
import type { GetTransaction200Response } from "../models";
// @ts-ignore
import type { ImportTransactions200Response } from "../models";
// @ts-ignore
import type { ImportTransactions201Response } from "../models";
// @ts-ignore
import type { ListTransactions200Response } from "../models";
// @ts-ignore
import type { UpdateTransactionRequest } from "../models";
/**
 * TransactionsApi - axios parameter creator
 */
export const TransactionsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Bulk delete transactions by ID
     * @param {BulkDeleteTransactionsRequest} bulkDeleteTransactionsRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    bulkDeleteTransactions: async (
      bulkDeleteTransactionsRequest: BulkDeleteTransactionsRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'bulkDeleteTransactionsRequest' is not null or undefined
      assertParamExists(
        "bulkDeleteTransactions",
        "bulkDeleteTransactionsRequest",
        bulkDeleteTransactionsRequest,
      );
      const localVarPath = `/api/v1/transactions/bulk`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        bulkDeleteTransactionsRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Create a new transaction
     * @param {CreateTransactionInput} createTransactionInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createTransaction: async (
      createTransactionInput: CreateTransactionInput,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createTransactionInput' is not null or undefined
      assertParamExists(
        "createTransaction",
        "createTransactionInput",
        createTransactionInput,
      );
      const localVarPath = `/api/v1/transactions`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createTransactionInput,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Delete a single transaction
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTransaction: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("deleteTransaction", "id", id);
      const localVarPath = `/api/v1/transactions/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Export transactions as CSV file
     * @param {string} [from]
     * @param {string} [to]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportTransactionsCsv: async (
      from?: string,
      to?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/transactions/export`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (from !== undefined) {
        localVarQueryParameter["from"] =
          (from as any) instanceof Date ? (from as any).toISOString() : from;
      }

      if (to !== undefined) {
        localVarQueryParameter["to"] =
          (to as any) instanceof Date ? (to as any).toISOString() : to;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Export all user data as JSON backup
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportTransactionsJson: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/transactions/export-json`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get a single transaction by ID
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTransaction: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("getTransaction", "id", id);
      const localVarPath = `/api/v1/transactions/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Upload CSV file, parse, and bulk insert transactions. Supports multiple exchange formats with auto-detection.
     * @param {CsvFormat} [format]
     * @param {string} [source] Custom data source name
     * @param {string} [userAddress] User wallet address (for blockchain explorers)
     * @param {string} [nativeAsset] Native asset symbol (for blockchain explorers)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    importTransactions: async (
      format?: CsvFormat,
      source?: string,
      userAddress?: string,
      nativeAsset?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/transactions/import`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (format !== undefined) {
        localVarQueryParameter["format"] = format;
      }

      if (source !== undefined) {
        localVarQueryParameter["source"] = source;
      }

      if (userAddress !== undefined) {
        localVarQueryParameter["userAddress"] = userAddress;
      }

      if (nativeAsset !== undefined) {
        localVarQueryParameter["nativeAsset"] = nativeAsset;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List transactions with pagination, filtering, and sorting
     * @param {number} [page]
     * @param {number} [limit]
     * @param {string} [asset]
     * @param {string} [type]
     * @param {string} [search]
     * @param {string} [from]
     * @param {string} [to]
     * @param {ListTransactionsSortEnum} [sort]
     * @param {ListTransactionsOrderEnum} [order]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listTransactions: async (
      page?: number,
      limit?: number,
      asset?: string,
      type?: string,
      search?: string,
      from?: string,
      to?: string,
      sort?: ListTransactionsSortEnum,
      order?: ListTransactionsOrderEnum,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/transactions`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (asset !== undefined) {
        localVarQueryParameter["asset"] = asset;
      }

      if (type !== undefined) {
        localVarQueryParameter["type"] = type;
      }

      if (search !== undefined) {
        localVarQueryParameter["search"] = search;
      }

      if (from !== undefined) {
        localVarQueryParameter["from"] =
          (from as any) instanceof Date ? (from as any).toISOString() : from;
      }

      if (to !== undefined) {
        localVarQueryParameter["to"] =
          (to as any) instanceof Date ? (to as any).toISOString() : to;
      }

      if (sort !== undefined) {
        localVarQueryParameter["sort"] = sort;
      }

      if (order !== undefined) {
        localVarQueryParameter["order"] = order;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Update a transaction
     * @param {string} id
     * @param {UpdateTransactionRequest} updateTransactionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateTransaction: async (
      id: string,
      updateTransactionRequest: UpdateTransactionRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("updateTransaction", "id", id);
      // verify required parameter 'updateTransactionRequest' is not null or undefined
      assertParamExists(
        "updateTransaction",
        "updateTransactionRequest",
        updateTransactionRequest,
      );
      const localVarPath = `/api/v1/transactions/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateTransactionRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TransactionsApi - functional programming interface
 */
export const TransactionsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    TransactionsApiAxiosParamCreator(configuration);
  return {
    /**
     * Bulk delete transactions by ID
     * @param {BulkDeleteTransactionsRequest} bulkDeleteTransactionsRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async bulkDeleteTransactions(
      bulkDeleteTransactionsRequest: BulkDeleteTransactionsRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<BulkDeleteTransactions200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.bulkDeleteTransactions(
          bulkDeleteTransactionsRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransactionsApi.bulkDeleteTransactions"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Create a new transaction
     * @param {CreateTransactionInput} createTransactionInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createTransaction(
      createTransactionInput: CreateTransactionInput,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<CreateTransaction201Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.createTransaction(
          createTransactionInput,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransactionsApi.createTransaction"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Delete a single transaction
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteTransaction(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteTransaction(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransactionsApi.deleteTransaction"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Export transactions as CSV file
     * @param {string} [from]
     * @param {string} [to]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async exportTransactionsCsv(
      from?: string,
      to?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.exportTransactionsCsv(
          from,
          to,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransactionsApi.exportTransactionsCsv"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Export all user data as JSON backup
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async exportTransactionsJson(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.exportTransactionsJson(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransactionsApi.exportTransactionsJson"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Get a single transaction by ID
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTransaction(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetTransaction200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTransaction(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransactionsApi.getTransaction"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Upload CSV file, parse, and bulk insert transactions. Supports multiple exchange formats with auto-detection.
     * @param {CsvFormat} [format]
     * @param {string} [source] Custom data source name
     * @param {string} [userAddress] User wallet address (for blockchain explorers)
     * @param {string} [nativeAsset] Native asset symbol (for blockchain explorers)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async importTransactions(
      format?: CsvFormat,
      source?: string,
      userAddress?: string,
      nativeAsset?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ImportTransactions200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.importTransactions(
          format,
          source,
          userAddress,
          nativeAsset,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransactionsApi.importTransactions"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List transactions with pagination, filtering, and sorting
     * @param {number} [page]
     * @param {number} [limit]
     * @param {string} [asset]
     * @param {string} [type]
     * @param {string} [search]
     * @param {string} [from]
     * @param {string} [to]
     * @param {ListTransactionsSortEnum} [sort]
     * @param {ListTransactionsOrderEnum} [order]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listTransactions(
      page?: number,
      limit?: number,
      asset?: string,
      type?: string,
      search?: string,
      from?: string,
      to?: string,
      sort?: ListTransactionsSortEnum,
      order?: ListTransactionsOrderEnum,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ListTransactions200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listTransactions(
          page,
          limit,
          asset,
          type,
          search,
          from,
          to,
          sort,
          order,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransactionsApi.listTransactions"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Update a transaction
     * @param {string} id
     * @param {UpdateTransactionRequest} updateTransactionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateTransaction(
      id: string,
      updateTransactionRequest: UpdateTransactionRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<GetTransaction200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.updateTransaction(
          id,
          updateTransactionRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransactionsApi.updateTransaction"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * TransactionsApi - factory interface
 */
export const TransactionsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = TransactionsApiFp(configuration);
  return {
    /**
     * Bulk delete transactions by ID
     * @param {TransactionsApiBulkDeleteTransactionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    bulkDeleteTransactions(
      requestParameters: TransactionsApiBulkDeleteTransactionsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<BulkDeleteTransactions200Response> {
      return localVarFp
        .bulkDeleteTransactions(
          requestParameters.bulkDeleteTransactionsRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Create a new transaction
     * @param {TransactionsApiCreateTransactionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createTransaction(
      requestParameters: TransactionsApiCreateTransactionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CreateTransaction201Response> {
      return localVarFp
        .createTransaction(requestParameters.createTransactionInput, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Delete a single transaction
     * @param {TransactionsApiDeleteTransactionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTransaction(
      requestParameters: TransactionsApiDeleteTransactionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<string> {
      return localVarFp
        .deleteTransaction(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Export transactions as CSV file
     * @param {TransactionsApiExportTransactionsCsvRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportTransactionsCsv(
      requestParameters: TransactionsApiExportTransactionsCsvRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<any> {
      return localVarFp
        .exportTransactionsCsv(
          requestParameters.from,
          requestParameters.to,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Export all user data as JSON backup
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportTransactionsJson(options?: RawAxiosRequestConfig): AxiosPromise<any> {
      return localVarFp
        .exportTransactionsJson(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Get a single transaction by ID
     * @param {TransactionsApiGetTransactionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTransaction(
      requestParameters: TransactionsApiGetTransactionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetTransaction200Response> {
      return localVarFp
        .getTransaction(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Upload CSV file, parse, and bulk insert transactions. Supports multiple exchange formats with auto-detection.
     * @param {TransactionsApiImportTransactionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    importTransactions(
      requestParameters: TransactionsApiImportTransactionsRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ImportTransactions200Response> {
      return localVarFp
        .importTransactions(
          requestParameters.format,
          requestParameters.source,
          requestParameters.userAddress,
          requestParameters.nativeAsset,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * List transactions with pagination, filtering, and sorting
     * @param {TransactionsApiListTransactionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listTransactions(
      requestParameters: TransactionsApiListTransactionsRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ListTransactions200Response> {
      return localVarFp
        .listTransactions(
          requestParameters.page,
          requestParameters.limit,
          requestParameters.asset,
          requestParameters.type,
          requestParameters.search,
          requestParameters.from,
          requestParameters.to,
          requestParameters.sort,
          requestParameters.order,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Update a transaction
     * @param {TransactionsApiUpdateTransactionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateTransaction(
      requestParameters: TransactionsApiUpdateTransactionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<GetTransaction200Response> {
      return localVarFp
        .updateTransaction(
          requestParameters.id,
          requestParameters.updateTransactionRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * TransactionsApi - interface
 */
export interface TransactionsApiInterface {
  /**
   * Bulk delete transactions by ID
   * @param {TransactionsApiBulkDeleteTransactionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  bulkDeleteTransactions(
    requestParameters: TransactionsApiBulkDeleteTransactionsRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<BulkDeleteTransactions200Response>;

  /**
   * Create a new transaction
   * @param {TransactionsApiCreateTransactionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  createTransaction(
    requestParameters: TransactionsApiCreateTransactionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<CreateTransaction201Response>;

  /**
   * Delete a single transaction
   * @param {TransactionsApiDeleteTransactionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  deleteTransaction(
    requestParameters: TransactionsApiDeleteTransactionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<string>;

  /**
   * Export transactions as CSV file
   * @param {TransactionsApiExportTransactionsCsvRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  exportTransactionsCsv(
    requestParameters?: TransactionsApiExportTransactionsCsvRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<any>;

  /**
   * Export all user data as JSON backup
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  exportTransactionsJson(options?: RawAxiosRequestConfig): AxiosPromise<any>;

  /**
   * Get a single transaction by ID
   * @param {TransactionsApiGetTransactionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getTransaction(
    requestParameters: TransactionsApiGetTransactionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetTransaction200Response>;

  /**
   * Upload CSV file, parse, and bulk insert transactions. Supports multiple exchange formats with auto-detection.
   * @param {TransactionsApiImportTransactionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  importTransactions(
    requestParameters?: TransactionsApiImportTransactionsRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ImportTransactions200Response>;

  /**
   * List transactions with pagination, filtering, and sorting
   * @param {TransactionsApiListTransactionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  listTransactions(
    requestParameters?: TransactionsApiListTransactionsRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ListTransactions200Response>;

  /**
   * Update a transaction
   * @param {TransactionsApiUpdateTransactionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  updateTransaction(
    requestParameters: TransactionsApiUpdateTransactionRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<GetTransaction200Response>;
}

/**
 * Request parameters for bulkDeleteTransactions operation in TransactionsApi.
 */
export interface TransactionsApiBulkDeleteTransactionsRequest {
  readonly bulkDeleteTransactionsRequest: BulkDeleteTransactionsRequest;
}

/**
 * Request parameters for createTransaction operation in TransactionsApi.
 */
export interface TransactionsApiCreateTransactionRequest {
  readonly createTransactionInput: CreateTransactionInput;
}

/**
 * Request parameters for deleteTransaction operation in TransactionsApi.
 */
export interface TransactionsApiDeleteTransactionRequest {
  readonly id: string;
}

/**
 * Request parameters for exportTransactionsCsv operation in TransactionsApi.
 */
export interface TransactionsApiExportTransactionsCsvRequest {
  readonly from?: string;

  readonly to?: string;
}

/**
 * Request parameters for getTransaction operation in TransactionsApi.
 */
export interface TransactionsApiGetTransactionRequest {
  readonly id: string;
}

/**
 * Request parameters for importTransactions operation in TransactionsApi.
 */
export interface TransactionsApiImportTransactionsRequest {
  readonly format?: CsvFormat;

  /**
   * Custom data source name
   */
  readonly source?: string;

  /**
   * User wallet address (for blockchain explorers)
   */
  readonly userAddress?: string;

  /**
   * Native asset symbol (for blockchain explorers)
   */
  readonly nativeAsset?: string;
}

/**
 * Request parameters for listTransactions operation in TransactionsApi.
 */
export interface TransactionsApiListTransactionsRequest {
  readonly page?: number;

  readonly limit?: number;

  readonly asset?: string;

  readonly type?: string;

  readonly search?: string;

  readonly from?: string;

  readonly to?: string;

  readonly sort?: ListTransactionsSortEnum;

  readonly order?: ListTransactionsOrderEnum;
}

/**
 * Request parameters for updateTransaction operation in TransactionsApi.
 */
export interface TransactionsApiUpdateTransactionRequest {
  readonly id: string;

  readonly updateTransactionRequest: UpdateTransactionRequest;
}

/**
 * TransactionsApi - object-oriented interface
 */
export class TransactionsApi
  extends BaseAPI
  implements TransactionsApiInterface
{
  /**
   * Bulk delete transactions by ID
   * @param {TransactionsApiBulkDeleteTransactionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public bulkDeleteTransactions(
    requestParameters: TransactionsApiBulkDeleteTransactionsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .bulkDeleteTransactions(
        requestParameters.bulkDeleteTransactionsRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Create a new transaction
   * @param {TransactionsApiCreateTransactionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createTransaction(
    requestParameters: TransactionsApiCreateTransactionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .createTransaction(requestParameters.createTransactionInput, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Delete a single transaction
   * @param {TransactionsApiDeleteTransactionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteTransaction(
    requestParameters: TransactionsApiDeleteTransactionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .deleteTransaction(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Export transactions as CSV file
   * @param {TransactionsApiExportTransactionsCsvRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public exportTransactionsCsv(
    requestParameters: TransactionsApiExportTransactionsCsvRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .exportTransactionsCsv(
        requestParameters.from,
        requestParameters.to,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Export all user data as JSON backup
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public exportTransactionsJson(options?: RawAxiosRequestConfig) {
    return TransactionsApiFp(this.configuration)
      .exportTransactionsJson(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get a single transaction by ID
   * @param {TransactionsApiGetTransactionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getTransaction(
    requestParameters: TransactionsApiGetTransactionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .getTransaction(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Upload CSV file, parse, and bulk insert transactions. Supports multiple exchange formats with auto-detection.
   * @param {TransactionsApiImportTransactionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public importTransactions(
    requestParameters: TransactionsApiImportTransactionsRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .importTransactions(
        requestParameters.format,
        requestParameters.source,
        requestParameters.userAddress,
        requestParameters.nativeAsset,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List transactions with pagination, filtering, and sorting
   * @param {TransactionsApiListTransactionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listTransactions(
    requestParameters: TransactionsApiListTransactionsRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .listTransactions(
        requestParameters.page,
        requestParameters.limit,
        requestParameters.asset,
        requestParameters.type,
        requestParameters.search,
        requestParameters.from,
        requestParameters.to,
        requestParameters.sort,
        requestParameters.order,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Update a transaction
   * @param {TransactionsApiUpdateTransactionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public updateTransaction(
    requestParameters: TransactionsApiUpdateTransactionRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .updateTransaction(
        requestParameters.id,
        requestParameters.updateTransactionRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}

export enum ListTransactionsSortEnum {
  TIMESTAMP = "timestamp",
  TYPE = "type",
  SENT_AMOUNT = "sentAmount",
  RECEIVED_AMOUNT = "receivedAmount",
  SENT_VALUE_USD = "sentValueUsd",
  RECEIVED_VALUE_USD = "receivedValueUsd",
  FEE_VALUE_USD = "feeValueUsd",
  UNKNOWN_DEFAULT_OPEN_API = "11184809",
}
export enum ListTransactionsOrderEnum {
  ASC = "asc",
  DESC = "desc",
  UNKNOWN_DEFAULT_OPEN_API = "11184809",
}
