
import __ASTRO_IMAGE_IMPORT_Z2anP5Y from "../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fen%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1xParz from "../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fde%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Uws4c from "../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffr%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1aQ8O9 from "../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fes%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZDtcdQ from "../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fja%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z11sdQh from "../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fko%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z10opqK from "../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fzh-CN%2Findex.mdx";
export default new Map([["../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fen%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z2anP5Y], ["../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fde%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1xParz], ["../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffr%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Uws4c], ["../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fes%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1aQ8O9], ["../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fja%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZDtcdQ], ["../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fko%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z11sdQh], ["../../../assets/logo-light.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fzh-CN%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z10opqK]]);
		